I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 278, in script
    "Left":
  File "game/script.rpy", line 288, in <module>
    $tnt = "false"
NameError: name 'tnt' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 278, in script
    "Left":
  File "E:\ProgrammingTools\renpy\renpy-7.3.5-sdk\renpy\ast.py", line 1628, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "E:\ProgrammingTools\renpy\renpy-7.3.5-sdk\renpy\exports.py", line 956, in menu
    condition = renpy.python.py_eval(condition)
  File "E:\ProgrammingTools\renpy\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\ProgrammingTools\renpy\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 288, in <module>
    $tnt = "false"
NameError: name 'tnt' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Cave Adventure 1.0
Sun Nov 03 16:36:51 2019
