I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 153, in script
    $ tnt = true
  File "game/script.rpy", line 153, in <module>
    $ tnt = true
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 153, in script
    $ tnt = true
  File "E:\ProgrammingTools\renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\ProgrammingTools\renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 153, in <module>
    $ tnt = true
NameError: name 'true' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Cave Adventure 1.0
Sun Nov 03 16:43:34 2019
